console.log(`__dirname: ${__dirname}`);
console.log(`__filename: ${__filename}`)
console.log(`process.pid: ${process.pid}`)
console.log(`process.env: ${process.env}`)
console.log(`process.env.PWD: ${process.env.PWD}`)
console.log(`process.platform: ${process.platform}`)
console.log(`process.versions: ${process.versions}`)
console.log(`process.cwd: ${process.cwd}`)
console.log(`process.uptime(): ${process.uptime()}`)